# Generated by Django 3.0.4 on 2020-03-28 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='classroom.Quiz'),
        ),
    ]
